### ISSUE TITLE
TIFFAppendToStrip: Maximum TIFF file size exceeded.

### ISSUE THREAD

**Issue by Nicholas-Schaub** [usnistgov/WIPP-EGT-plugin#1]
When analyzing a large image (43047×29411 pixels, 16-bit) the logs display the following message:
```bash
TIFFAppendToStrip: Maximum TIFF file size exceeded.
```

Does this indicate that big tiffs are not supported?

**Comment by antoinegerardin** [comment]
BigTiff should be supported. A flag is missing in the packaged version. It will be updated soon. Thanks for bringing this to our attention.

**Comment by antoinegerardin** [comment]
FIX in commit 1aef889e76328850a8e28da959c80e1359b1d75d
