### ISSUE TITLE
Support for compression

### ISSUE THREAD

**Issue by Nicholas-Schaub** [usnistgov/WIPP-EGT-plugin#2]
It does not appear as though the output of this plugin is a compressed tiff (at least for labeled images, I have not tested binary images). Are there plans to output compressed images?

**Comment by antoinegerardin** [comment]
We do not compress the output at this point. Should this be optional or mandatory? LZW only or other option as well?

**Comment by Nicholas-Schaub** [comment]
Most WIPP plugins appear to compress automatically using LZW. I think sticking with LZW compression by default would keep this in sync with other WIPP plugins.

**Comment by antoinegerardin** [comment]
FIX in commit 1aef889e76328850a8e28da959c80e1359b1d75d
