### ISSUE TITLE
Enable setting a greedy parameter for the plugin

### ISSUE THREAD

**Issue by pbajcsy** [usnistgov/WIPP-EGT-plugin#5]
Description:
Success of the EGT algorithm depends on the user-driven greedy parameter which is currently not accessible from the plugin manifest based user interface.

Proposal:
Add to the plugin manifest (JSON file) the user interface for the greedy parameter and parse the parameter when launching the plugin.

Additional context:
Here is the snapshot of the user interface for the same code in ImageJ/Fiji.

![ui](https://user-images.githubusercontent.com/1915644/72007639-1f147c80-3220-11ea-80c9-a895f7bfd88e.png)

**Comment by antoinegerardin** [comment]
Fixed in commit  c1ae2ab7e260debe7274933004fc5731164c5d3f
